const hre = require("hardhat");
const fs = require("node:fs");
const path = require("node:path");

const LOCAL_ACCOUNTS = {
  DEPLOYER_PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
  PRIVKEY_GOVT_OFFICIAL: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
  PRIVKEY_AUDITOR: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
  PRIVKEY_CONTRACTOR_1: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
  PRIVKEY_CONTRACTOR_2: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6",
  PRIVKEY_INSPECTOR: "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e",
};

async function writeLocalDeployment(addresses) {
  const network = await hre.ethers.provider.getNetwork();
  const isLocal =
    hre.network.name === "localhost" ||
    hre.network.name === "hardhat" ||
    network.chainId === 31337n;

  const deployment = {
    network: hre.network.name,
    chainId: Number(network.chainId),
    rpcUrl: process.env.HARDHAT_RPC_URL || "http://127.0.0.1:8545",
    deployedAt: new Date().toISOString(),
    contracts: addresses,
  };

  const deploymentsDir = path.resolve(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });
  fs.writeFileSync(
    path.join(deploymentsDir, `${hre.network.name}.json`),
    `${JSON.stringify(deployment, null, 2)}\n`,
  );

  if (!isLocal) return;

  const rootEnvPath = path.resolve(__dirname, "..", "..", ".env.localchain");
  const envLines = [
    "# Generated by pnpm run chain:deploy. Do not commit real private keys here.",
    `HARDHAT_RPC_URL=${deployment.rpcUrl}`,
    "VITE_BLOCK_EXPLORER_URL=",
    ...Object.entries(LOCAL_ACCOUNTS).map(([key, value]) => `${key}=${value}`),
    `ROLE_MANAGER_ADDRESS=${addresses.RoleManager}`,
    `PROJECT_REGISTRY_ADDRESS=${addresses.ProjectRegistry}`,
    `MILESTONE_ESCROW_ADDRESS=${addresses.MilestoneEscrow}`,
    `VITE_ROLE_MANAGER_ADDRESS=${addresses.RoleManager}`,
    `VITE_PROJECT_REGISTRY_ADDRESS=${addresses.ProjectRegistry}`,
    `VITE_MILESTONE_ESCROW_ADDRESS=${addresses.MilestoneEscrow}`,
    "",
  ];

  fs.writeFileSync(rootEnvPath, `${envLines.join("\n")}`);
  console.log(`\nWrote local app env to ${rootEnvPath}`);
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();

  const RoleManager = await hre.ethers.getContractFactory("RoleManager");
  const roleManager = await RoleManager.deploy();
  await roleManager.waitForDeployment();

  const ProjectRegistry = await hre.ethers.getContractFactory("ProjectRegistry");
  const projectRegistry = await ProjectRegistry.deploy(await roleManager.getAddress());
  await projectRegistry.waitForDeployment();

  const MilestoneEscrow = await hre.ethers.getContractFactory("MilestoneEscrow");
  const milestoneEscrow = await MilestoneEscrow.deploy(
    await projectRegistry.getAddress(),
    await roleManager.getAddress()
  );
  await milestoneEscrow.waitForDeployment();

  const GOVT_OFFICIAL = await roleManager.GOVT_OFFICIAL();
  const AUDITOR       = await roleManager.AUDITOR();
  const CONTRACTOR    = await roleManager.CONTRACTOR();
  const INSPECTOR     = await roleManager.INSPECTOR();
  const CITIZEN       = await roleManager.CITIZEN();

  // Predefined demo accounts matching frontend login page and backend seed users
  const accounts = [
    { address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", role: GOVT_OFFICIAL, label: "Government Official" },
    { address: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8", role: AUDITOR,       label: "Auditor" },
    { address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC", role: CONTRACTOR,    label: "Contractor 1" },
    { address: "0x90F79bf6EB2c4f870365E785982E1f101E93b906", role: CONTRACTOR,    label: "Contractor 2" },
    { address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199", role: INSPECTOR,     label: "Field Inspector" },
    { address: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65", role: CITIZEN,       label: "Citizen 1" },
    { address: "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc", role: CITIZEN,       label: "Citizen 2" },
  ];

  for (const account of accounts) {
    await roleManager.grantUserRole(account.address, account.role);
    console.log(`Granted ${account.label} role to ${account.address}`);
  }

  const addresses = {
    RoleManager: await roleManager.getAddress(),
    ProjectRegistry: await projectRegistry.getAddress(),
    MilestoneEscrow: await milestoneEscrow.getAddress(),
  };

  await writeLocalDeployment(addresses);

  console.log("\nDeployed contract addresses:");
  console.table(addresses);

  console.log("\nCopy these into your .env file:");
  console.log(`ROLE_MANAGER_ADDRESS=${addresses.RoleManager}`);
  console.log(`PROJECT_REGISTRY_ADDRESS=${addresses.ProjectRegistry}`);
  console.log(`MILESTONE_ESCROW_ADDRESS=${addresses.MilestoneEscrow}`);
  console.log(`VITE_ROLE_MANAGER_ADDRESS=${addresses.RoleManager}`);
  console.log(`VITE_PROJECT_REGISTRY_ADDRESS=${addresses.ProjectRegistry}`);
  console.log(`VITE_MILESTONE_ESCROW_ADDRESS=${addresses.MilestoneEscrow}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
